# Generated by Django 5.0.2 on 2024-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("uname", models.CharField(max_length=50)),
                ("fname", models.CharField(max_length=50)),
                ("unumber", models.IntegerField()),
                ("uemail", models.EmailField(max_length=30)),
                ("upass", models.CharField(max_length=50)),
            ],
        ),
    ]
